<?php
/**
 * Module : Formulaire de page protégée par mot de passe
 *
 * Remplace le formulaire WordPress par défaut affiché sur les pages
 * protégées par un mot de passe avec un design adapté au thème Piscines Mova.
 *
 * @package HelloElementorChild
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Enqueue the password form stylesheet.
 */
function mova_password_form_enqueue_styles() {
	wp_enqueue_style(
		'mova-password-form',
		get_stylesheet_directory_uri() . '/assets/css/password-form.css',
		[],
		HELLO_ELEMENTOR_CHILD_VERSION
	);
}
add_action( 'wp_enqueue_scripts', 'mova_password_form_enqueue_styles' );

/**
 * Override the default WordPress password-protected page form.
 *
 * @param  string $output The default HTML form generated by WordPress.
 * @return string         The custom HTML form.
 */
function mova_custom_password_form( $output ) {
	global $post;

	$label = 'pwbox-' . ( empty( $post->ID ) ? rand() : $post->ID );
	$action_url = esc_url( site_url( 'wp-login.php?action=postpass', 'login_post' ) );

	ob_start();
	?>
	<div class="mova-password-form-wrap">
		<div class="mova-password-form-inner">

			<div class="mova-password-form-icon" aria-hidden="true">
				<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 24 24" fill="none"
					stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
					<rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect>
					<path d="M7 11V7a5 5 0 0 1 10 0v4"></path>
				</svg>
			</div>

			<h2 class="mova-password-form-title">
				<?php esc_html_e( 'Contenu protégé', 'piscines-mova' ); ?>
			</h2>

			<p class="mova-password-form-description">
				<?php esc_html_e( 'Ce contenu est protégé par un mot de passe. Veuillez le saisir ci-dessous pour y accéder.', 'piscines-mova' ); ?>
			</p>

			<form class="mova-password-form" action="<?php echo $action_url; ?>" method="post">

				<div class="mova-password-form-field">
					<label class="mova-password-form-label" for="<?php echo esc_attr( $label ); ?>">
						<?php esc_html_e( 'Mot de passe', 'piscines-mova' ); ?>
					</label>
					<div class="mova-password-form-input-wrap">
						<input
							class="mova-password-form-input"
							type="password"
							name="post_password"
							id="<?php echo esc_attr( $label ); ?>"
							autocomplete="current-password"
							placeholder="<?php esc_attr_e( 'Entrez le mot de passe…', 'piscines-mova' ); ?>"
							required
						/>
						<button
							type="button"
							class="mova-password-toggle"
							aria-label="<?php esc_attr_e( 'Afficher / masquer le mot de passe', 'piscines-mova' ); ?>"
						>
							<svg class="mova-eye-show" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"
								fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">
								<path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
								<circle cx="12" cy="12" r="3"></circle>
							</svg>
							<svg class="mova-eye-hide" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"
								fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"
								style="display:none">
								<path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94"></path>
								<path d="M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19"></path>
								<line x1="1" y1="1" x2="23" y2="23"></line>
							</svg>
						</button>
					</div>
				</div>

				<button type="submit" class="mova-password-form-submit">
					<?php esc_html_e( 'Accéder au contenu', 'piscines-mova' ); ?>
				</button>

			</form>
		</div>
	</div>

	<script>
	(function () {
		var btn   = document.querySelector('.mova-password-toggle');
		var input = document.querySelector('.mova-password-form-input');
		if (!btn || !input) return;
		btn.addEventListener('click', function () {
			var isPassword = input.type === 'password';
			input.type = isPassword ? 'text' : 'password';
			btn.querySelector('.mova-eye-show').style.display = isPassword ? 'none'  : '';
			btn.querySelector('.mova-eye-hide').style.display = isPassword ? ''      : 'none';
		});
	})();
	</script>
	<?php
	return ob_get_clean();
}
add_filter( 'the_password_form', 'mova_custom_password_form' );

/**
 * Disable wpautop on password-protected pages so it doesn't inject <br> tags
 * into the custom form HTML.
 */
function mova_disable_wpautop_on_password_form() {
	if ( post_password_required() ) {
		remove_filter( 'the_content', 'wpautop' );
	}
}
add_action( 'wp', 'mova_disable_wpautop_on_password_form' );
